<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->increments('id');
            $table->string('iso',2)->unique();
            $table->string('iso3',3)->nullable();
            $table->string('name',95)->nullable();
            $table->string('nice_name',95)->nullable();
            $table->string('num_code',5)->nullable();
            $table->string('phone_code',8)->nullable();
            $table->string('currency',4)->nullable();
            $table->string('timezone',55)->nullable();
            $table->boolean('status')->default(1);
            $table->dateTime('created_at')->nullable();
            $table->integer('created_by',false)->nullable();
        });

        $tb_countries = array(
            array('iso' => 'AF','iso3' => 'AFG','name' => 'AFGHANISTAN','nice_name' => 'Afghanistan','num_code' => '4','phone_code' => '93','currency' => 'AFN','timezone' => 'Asia/Kabul','status' => '1'),
            array('iso' => 'AL','iso3' => 'ALB','name' => 'ALBANIA','nice_name' => 'Albania','num_code' => '8','phone_code' => '355','currency' => 'ALL','timezone' => 'Europe/Tirane','status' => '1'),
            array('iso' => 'DZ','iso3' => 'DZA','name' => 'ALGERIA','nice_name' => 'Algeria','num_code' => '12','phone_code' => '213','currency' => 'DZD','timezone' => 'Africa/Algiers','status' => '1'),
            array('iso' => 'AS','iso3' => 'ASM','name' => 'AMERICAN SAMOA','nice_name' => 'American Samoa','num_code' => '16','phone_code' => '1684','currency' => '','timezone' => 'Pacific/Pago_Pago','status' => '1'),
            array('iso' => 'AD','iso3' => 'AND','name' => 'ANDORRA','nice_name' => 'Andorra','num_code' => '20','phone_code' => '376','currency' => 'EUR','timezone' => 'Europe/Andorra','status' => '1'),
            array('iso' => 'AO','iso3' => 'AGO','name' => 'ANGOLA','nice_name' => 'Angola','num_code' => '24','phone_code' => '244','currency' => 'AOA','timezone' => 'Africa/Luanda','status' => '1'),
            array('iso' => 'AI','iso3' => 'AIA','name' => 'ANGUILLA','nice_name' => 'Anguilla','num_code' => '660','phone_code' => '1264','currency' => 'XCD','timezone' => 'America/Anguilla','status' => '1'),
            array('iso' => 'AQ','iso3' => NULL,'name' => 'ANTARCTICA','nice_name' => 'Antarctica','num_code' => NULL,'phone_code' => '0','currency' => '','timezone' => 'Antarctica/Casey','status' => '1'),
            array('iso' => 'AG','iso3' => 'ATG','name' => 'ANTIGUA AND BARBUDA','nice_name' => 'Antigua and Barbuda','num_code' => '28','phone_code' => '1268','currency' => 'XCD','timezone' => 'America/Antigua','status' => '1'),
            array('iso' => 'AR','iso3' => 'ARG','name' => 'ARGENTINA','nice_name' => 'Argentina','num_code' => '32','phone_code' => '54','currency' => 'ARS','timezone' => 'America/Argentina/Buenos_Aires','status' => '1'),
            array('iso' => 'AM','iso3' => 'ARM','name' => 'ARMENIA','nice_name' => 'Armenia','num_code' => '51','phone_code' => '374','currency' => 'AMD','timezone' => 'Asia/Yerevan','status' => '1'),
            array('iso' => 'AW','iso3' => 'ABW','name' => 'ARUBA','nice_name' => 'Aruba','num_code' => '533','phone_code' => '297','currency' => 'AWG','timezone' => 'America/Aruba','status' => '1'),
            array('iso' => 'AU','iso3' => 'AUS','name' => 'AUSTRALIA','nice_name' => 'Australia','num_code' => '36','phone_code' => '61','currency' => '','timezone' => 'Antarctica/Macquarie','status' => '1'),
            array('iso' => 'AT','iso3' => 'AUT','name' => 'AUSTRIA','nice_name' => 'Austria','num_code' => '40','phone_code' => '43','currency' => 'EUR','timezone' => 'Europe/Vienna','status' => '1'),
            array('iso' => 'AZ','iso3' => 'AZE','name' => 'AZERBAIJAN','nice_name' => 'Azerbaijan','num_code' => '31','phone_code' => '994','currency' => 'AZN','timezone' => 'Asia/Baku','status' => '1'),
            array('iso' => 'BS','iso3' => 'BHS','name' => 'BAHAMAS','nice_name' => 'Bahamas','num_code' => '44','phone_code' => '1242','currency' => '','timezone' => 'America/Nassau','status' => '1'),
            array('iso' => 'BH','iso3' => 'BHR','name' => 'BAHRAIN','nice_name' => 'Bahrain','num_code' => '48','phone_code' => '973','currency' => 'BHD','timezone' => 'Asia/Bahrain','status' => '1'),
            array('iso' => 'BD','iso3' => 'BGD','name' => 'BANGLADESH','nice_name' => 'Bangladesh','num_code' => '50','phone_code' => '880','currency' => 'BDT','timezone' => 'Asia/Dhaka','status' => '1'),
            array('iso' => 'BB','iso3' => 'BRB','name' => 'BARBADOS','nice_name' => 'Barbados','num_code' => '52','phone_code' => '1246','currency' => 'BBD','timezone' => 'America/Barbados','status' => '1'),
            array('iso' => 'BY','iso3' => 'BLR','name' => 'BELARUS','nice_name' => 'Belarus','num_code' => '112','phone_code' => '375','currency' => 'BYR','timezone' => 'Europe/Minsk','status' => '1'),
            array('iso' => 'BE','iso3' => 'BEL','name' => 'BELGIUM','nice_name' => 'Belgium','num_code' => '56','phone_code' => '32','currency' => 'EUR','timezone' => 'Europe/Brussels','status' => '1'),
            array('iso' => 'BZ','iso3' => 'BLZ','name' => 'BELIZE','nice_name' => 'Belize','num_code' => '84','phone_code' => '501','currency' => 'BZD','timezone' => 'America/Belize','status' => '1'),
            array('iso' => 'BJ','iso3' => 'BEN','name' => 'BENIN','nice_name' => 'Benin','num_code' => '204','phone_code' => '229','currency' => 'XOF','timezone' => 'Africa/Porto-Novo','status' => '1'),
            array('iso' => 'BM','iso3' => 'BMU','name' => 'BERMUDA','nice_name' => 'Bermuda','num_code' => '60','phone_code' => '1441','currency' => 'BMD','timezone' => 'Atlantic/Bermuda','status' => '1'),
            array('iso' => 'BT','iso3' => 'BTN','name' => 'BHUTAN','nice_name' => 'Bhutan','num_code' => '64','phone_code' => '975','currency' => 'BTN','timezone' => 'Asia/Thimphu','status' => '1'),
            array('iso' => 'BO','iso3' => 'BOL','name' => 'BOLIVIA','nice_name' => 'Bolivia','num_code' => '68','phone_code' => '591','currency' => 'BOB','timezone' => 'America/La_Paz','status' => '1'),
            array('iso' => 'BA','iso3' => 'BIH','name' => 'BOSNIA AND HERZEGOVINA','nice_name' => 'Bosnia and Herzegovina','num_code' => '70','phone_code' => '387','currency' => 'BAM','timezone' => 'Europe/Sarajevo','status' => '1'),
            array('iso' => 'BW','iso3' => 'BWA','name' => 'BOTSWANA','nice_name' => 'Botswana','num_code' => '72','phone_code' => '267','currency' => 'BWP','timezone' => 'Africa/Gaborone','status' => '1'),
            array('iso' => 'BV','iso3' => NULL,'name' => 'BOUVET ISLAND','nice_name' => 'Bouvet Island','num_code' => NULL,'phone_code' => '0','currency' => '','timezone' => '','status' => '1'),
            array('iso' => 'BR','iso3' => 'BRA','name' => 'BRAZIL','nice_name' => 'Brazil','num_code' => '76','phone_code' => '55','currency' => 'BRL','timezone' => 'America/Araguaina','status' => '1'),
            array('iso' => 'IO','iso3' => NULL,'name' => 'BRITISH INDIAN OCEAN TERRITORY','nice_name' => 'British Indian Ocean Territory','num_code' => NULL,'phone_code' => '246','currency' => 'USD','timezone' => 'Indian/Chagos','status' => '1'),
            array('iso' => 'BN','iso3' => 'BRN','name' => 'BRUNEI DARUSSALAM','nice_name' => 'Brunei Darussalam','num_code' => '96','phone_code' => '673','currency' => 'BND','timezone' => 'Asia/Brunei','status' => '1'),
            array('iso' => 'BG','iso3' => 'BGR','name' => 'BULGARIA','nice_name' => 'Bulgaria','num_code' => '100','phone_code' => '359','currency' => 'BGN','timezone' => 'Europe/Sofia','status' => '1'),
            array('iso' => 'BF','iso3' => 'BFA','name' => 'BURKINA FASO','nice_name' => 'Burkina Faso','num_code' => '854','phone_code' => '226','currency' => 'XOF','timezone' => 'Africa/Ouagadougou','status' => '1'),
            array('iso' => 'BI','iso3' => 'BDI','name' => 'BURUNDI','nice_name' => 'Burundi','num_code' => '108','phone_code' => '257','currency' => 'BIF','timezone' => 'Africa/Bujumbura','status' => '1'),
            array('iso' => 'KH','iso3' => 'KHM','name' => 'CAMBODIA','nice_name' => 'Cambodia','num_code' => '116','phone_code' => '855','currency' => 'KHR','timezone' => 'Asia/Phnom_Penh','status' => '1'),
            array('iso' => 'CM','iso3' => 'CMR','name' => 'CAMEROON','nice_name' => 'Cameroon','num_code' => '120','phone_code' => '237','currency' => 'XAF','timezone' => 'Africa/Douala','status' => '1'),
            array('iso' => 'CA','iso3' => 'CAN','name' => 'CANADA','nice_name' => 'Canada','num_code' => '124','phone_code' => '1','currency' => '','timezone' => 'America/Atikokan','status' => '1'),
            array('iso' => 'CV','iso3' => 'CPV','name' => 'CAPE VERDE','nice_name' => 'Cape Verde','num_code' => '132','phone_code' => '238','currency' => 'CVE','timezone' => 'Atlantic/Cape_Verde','status' => '1'),
            array('iso' => 'KY','iso3' => 'CYM','name' => 'CAYMAN ISLANDS','nice_name' => 'Cayman Islands','num_code' => '136','phone_code' => '1345','currency' => 'KYD','timezone' => 'America/Cayman','status' => '1'),
            array('iso' => 'CF','iso3' => 'CAF','name' => 'CENTRAL AFRICAN REPUBLIC','nice_name' => 'Central African Republic','num_code' => '140','phone_code' => '236','currency' => 'XAF','timezone' => 'Africa/Bangui','status' => '1'),
            array('iso' => 'TD','iso3' => 'TCD','name' => 'CHAD','nice_name' => 'Chad','num_code' => '148','phone_code' => '235','currency' => 'XAF','timezone' => 'Africa/Ndjamena','status' => '1'),
            array('iso' => 'CL','iso3' => 'CHL','name' => 'CHILE','nice_name' => 'Chile','num_code' => '152','phone_code' => '56','currency' => 'CLP','timezone' => 'America/Santiago','status' => '1'),
            array('iso' => 'CN','iso3' => 'CHN','name' => 'CHINA','nice_name' => 'China','num_code' => '156','phone_code' => '86','currency' => 'CNY','timezone' => 'Asia/Shanghai','status' => '1'),
            array('iso' => 'CX','iso3' => NULL,'name' => 'CHRISTMAS ISLAND','nice_name' => 'Christmas Island','num_code' => NULL,'phone_code' => '61','currency' => '','timezone' => 'Indian/Christmas','status' => '1'),
            array('iso' => 'CC','iso3' => NULL,'name' => 'COCOS (KEELING) ISLANDS','nice_name' => 'Cocos (Keeling) Islands','num_code' => NULL,'phone_code' => '672','currency' => '','timezone' => 'Indian/Cocos','status' => '1'),
            array('iso' => 'CO','iso3' => 'COL','name' => 'COLOMBIA','nice_name' => 'Colombia','num_code' => '170','phone_code' => '57','currency' => 'COP','timezone' => 'America/Bogota','status' => '1'),
            array('iso' => 'KM','iso3' => 'COM','name' => 'COMOROS','nice_name' => 'Comoros','num_code' => '174','phone_code' => '269','currency' => '','timezone' => 'Indian/Comoro','status' => '1'),
            array('iso' => 'CG','iso3' => 'COG','name' => 'CONGO','nice_name' => 'Congo','num_code' => '178','phone_code' => '242','currency' => '','timezone' => 'Africa/Brazzaville','status' => '1'),
            array('iso' => 'CD','iso3' => 'COD','name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE','nice_name' => 'Congo, the Democratic Republic of the','num_code' => '180','phone_code' => '242','currency' => '','timezone' => 'Africa/Kinshasa','status' => '1'),
            array('iso' => 'CK','iso3' => 'COK','name' => 'COOK ISLANDS','nice_name' => 'Cook Islands','num_code' => '184','phone_code' => '682','currency' => 'NZD','timezone' => 'Pacific/Rarotonga','status' => '1'),
            array('iso' => 'CR','iso3' => 'CRI','name' => 'COSTA RICA','nice_name' => 'Costa Rica','num_code' => '188','phone_code' => '506','currency' => 'CRC','timezone' => 'America/Costa_Rica','status' => '1'),
            array('iso' => 'CI','iso3' => 'CIV','name' => 'COTE D\'IVOIRE','nice_name' => 'Ivorycost','num_code' => '384','phone_code' => '225','currency' => '','timezone' => 'Africa/Abidjan','status' => '1'),
            array('iso' => 'HR','iso3' => 'HRV','name' => 'CROATIA','nice_name' => 'Croatia','num_code' => '191','phone_code' => '385','currency' => '','timezone' => 'Europe/Zagreb','status' => '1'),
            array('iso' => 'CU','iso3' => 'CUB','name' => 'CUBA','nice_name' => 'Cuba','num_code' => '192','phone_code' => '53','currency' => 'CUC','timezone' => 'America/Havana','status' => '1'),
            array('iso' => 'CY','iso3' => 'CYP','name' => 'CYPRUS','nice_name' => 'Cyprus','num_code' => '196','phone_code' => '357','currency' => 'EUR','timezone' => 'Asia/Nicosia','status' => '1'),
            array('iso' => 'CZ','iso3' => 'CZE','name' => 'CZECH REPUBLIC','nice_name' => 'Czech Republic','num_code' => '203','phone_code' => '420','currency' => 'CZK','timezone' => 'Europe/Prague','status' => '1'),
            array('iso' => 'DK','iso3' => 'DNK','name' => 'DENMARK','nice_name' => 'Denmark','num_code' => '208','phone_code' => '45','currency' => 'DKK','timezone' => 'Europe/Copenhagen','status' => '1'),
            array('iso' => 'DJ','iso3' => 'DJI','name' => 'DJIBOUTI','nice_name' => 'Djibouti','num_code' => '262','phone_code' => '253','currency' => 'DJF','timezone' => 'Africa/Djibouti','status' => '1'),
            array('iso' => 'DM','iso3' => 'DMA','name' => 'DOMINICA','nice_name' => 'Dominica','num_code' => '212','phone_code' => '1767','currency' => 'XCD','timezone' => 'America/Dominica','status' => '1'),
            array('iso' => 'DO','iso3' => 'DOM','name' => 'DOMINICAN REPUBLIC','nice_name' => 'Dominican Republic','num_code' => '214','phone_code' => '1809','currency' => 'DOP','timezone' => 'America/Santo_Domingo','status' => '1'),
            array('iso' => 'EC','iso3' => 'ECU','name' => 'ECUADOR','nice_name' => 'Ecuador','num_code' => '218','phone_code' => '593','currency' => 'USD','timezone' => 'America/Guayaquil','status' => '1'),
            array('iso' => 'EG','iso3' => 'EGY','name' => 'EGYPT','nice_name' => 'Egypt','num_code' => '818','phone_code' => '20','currency' => 'EGP','timezone' => 'Africa/Cairo','status' => '1'),
            array('iso' => 'SV','iso3' => 'SLV','name' => 'EL SALVADOR','nice_name' => 'El Salvador','num_code' => '222','phone_code' => '503','currency' => 'USD','timezone' => 'America/El_Salvador','status' => '1'),
            array('iso' => 'GQ','iso3' => 'GNQ','name' => 'EQUATORIAL GUINEA','nice_name' => 'Equatorial Guinea','num_code' => '226','phone_code' => '240','currency' => 'XAF','timezone' => 'Africa/Malabo','status' => '1'),
            array('iso' => 'ER','iso3' => 'ERI','name' => 'ERITREA','nice_name' => 'Eritrea','num_code' => '232','phone_code' => '291','currency' => 'ERN','timezone' => 'Africa/Asmara','status' => '1'),
            array('iso' => 'EE','iso3' => 'EST','name' => 'ESTONIA','nice_name' => 'Estonia','num_code' => '233','phone_code' => '372','currency' => 'EUR','timezone' => 'Europe/Tallinn','status' => '1'),
            array('iso' => 'ET','iso3' => 'ETH','name' => 'ETHIOPIA','nice_name' => 'Ethiopia','num_code' => '231','phone_code' => '251','currency' => 'ETB','timezone' => 'Africa/Addis_Ababa','status' => '1'),
            array('iso' => 'FK','iso3' => 'FLK','name' => 'FALKLAND ISLANDS (MALVINAS)','nice_name' => 'Falkland Islands (Malvinas)','num_code' => '238','phone_code' => '500','currency' => 'FKP','timezone' => 'Atlantic/Stanley','status' => '1'),
            array('iso' => 'FO','iso3' => 'FRO','name' => 'FAROE ISLANDS','nice_name' => 'Faroe Islands','num_code' => '234','phone_code' => '298','currency' => 'DKK','timezone' => 'Atlantic/Faroe','status' => '1'),
            array('iso' => 'FJ','iso3' => 'FJI','name' => 'FIJI','nice_name' => 'Fiji','num_code' => '242','phone_code' => '679','currency' => '','timezone' => 'Pacific/Fiji','status' => '1'),
            array('iso' => 'FI','iso3' => 'FIN','name' => 'FINLAND','nice_name' => 'Finland','num_code' => '246','phone_code' => '358','currency' => 'EUR','timezone' => 'Europe/Helsinki','status' => '1'),
            array('iso' => 'FR','iso3' => 'FRA','name' => 'FRANCE','nice_name' => 'France','num_code' => '250','phone_code' => '33','currency' => 'EUR','timezone' => 'Europe/Paris','status' => '1'),
            array('iso' => 'GF','iso3' => 'GUF','name' => 'FRENCH GUIANA','nice_name' => 'French Guiana','num_code' => '254','phone_code' => '594','currency' => '','timezone' => 'America/Cayenne','status' => '1'),
            array('iso' => 'PF','iso3' => 'PYF','name' => 'FRENCH POLYNESIA','nice_name' => 'French Polynesia','num_code' => '258','phone_code' => '689','currency' => 'XPF','timezone' => 'Pacific/Gambier','status' => '1'),
            array('iso' => 'TF','iso3' => NULL,'name' => 'FRENCH SOUTHERN TERRITORIES','nice_name' => 'French Southern Territories','num_code' => NULL,'phone_code' => '0','currency' => '','timezone' => 'Indian/Kerguelen','status' => '1'),
            array('iso' => 'GA','iso3' => 'GAB','name' => 'GABON','nice_name' => 'Gabon','num_code' => '266','phone_code' => '241','currency' => 'XAF','timezone' => 'Africa/Libreville','status' => '1'),
            array('iso' => 'GM','iso3' => 'GMB','name' => 'GAMBIA','nice_name' => 'Gambia','num_code' => '270','phone_code' => '220','currency' => '','timezone' => 'Africa/Banjul','status' => '1'),
            array('iso' => 'GE','iso3' => 'GEO','name' => 'GEORGIA','nice_name' => 'Georgia','num_code' => '268','phone_code' => '995','currency' => 'GEL','timezone' => 'Asia/Tbilisi','status' => '1'),
            array('iso' => 'DE','iso3' => 'DEU','name' => 'GERMANY','nice_name' => 'Germany','num_code' => '276','phone_code' => '49','currency' => 'EUR','timezone' => 'Europe/Berlin','status' => '1'),
            array('iso' => 'GH','iso3' => 'GHA','name' => 'GHANA','nice_name' => 'Ghana','num_code' => '288','phone_code' => '233','currency' => 'GHS','timezone' => 'Africa/Accra','status' => '1'),
            array('iso' => 'GI','iso3' => 'GIB','name' => 'GIBRALTAR','nice_name' => 'Gibraltar','num_code' => '292','phone_code' => '350','currency' => 'GIP','timezone' => 'Europe/Gibraltar','status' => '1'),
            array('iso' => 'GR','iso3' => 'GRC','name' => 'GREECE','nice_name' => 'Greece','num_code' => '300','phone_code' => '30','currency' => 'EUR','timezone' => 'Europe/Athens','status' => '1'),
            array('iso' => 'GL','iso3' => 'GRL','name' => 'GREENLAND','nice_name' => 'Greenland','num_code' => '304','phone_code' => '299','currency' => '','timezone' => 'America/Danmarkshavn','status' => '1'),
            array('iso' => 'GD','iso3' => 'GRD','name' => 'GRENADA','nice_name' => 'Grenada','num_code' => '308','phone_code' => '1473','currency' => 'XCD','timezone' => 'America/Grenada','status' => '1'),
            array('iso' => 'GP','iso3' => 'GLP','name' => 'GUADELOUPE','nice_name' => 'Guadeloupe','num_code' => '312','phone_code' => '590','currency' => '','timezone' => 'America/Guadeloupe','status' => '1'),
            array('iso' => 'GU','iso3' => 'GUM','name' => 'GUAM','nice_name' => 'Guam','num_code' => '316','phone_code' => '1671','currency' => '','timezone' => 'Pacific/Guam','status' => '1'),
            array('iso' => 'GT','iso3' => 'GTM','name' => 'GUATEMALA','nice_name' => 'Guatemala','num_code' => '320','phone_code' => '502','currency' => 'GTQ','timezone' => 'America/Guatemala','status' => '1'),
            array('iso' => 'GN','iso3' => 'GIN','name' => 'GUINEA','nice_name' => 'Guinea','num_code' => '324','phone_code' => '224','currency' => 'GNF','timezone' => 'Africa/Conakry','status' => '1'),
            array('iso' => 'GW','iso3' => 'GNB','name' => 'GUINEA-BISSAU','nice_name' => 'Guinea-Bissau','num_code' => '624','phone_code' => '245','currency' => 'XOF','timezone' => 'Africa/Bissau','status' => '1'),
            array('iso' => 'GY','iso3' => 'GUY','name' => 'GUYANA','nice_name' => 'Guyana','num_code' => '328','phone_code' => '592','currency' => 'GYD','timezone' => 'America/Guyana','status' => '1'),
            array('iso' => 'HT','iso3' => 'HTI','name' => 'HAITI','nice_name' => 'Haiti','num_code' => '332','phone_code' => '509','currency' => 'HTG','timezone' => 'America/Port-au-Prince','status' => '1'),
            array('iso' => 'HM','iso3' => NULL,'name' => 'HEARD ISLAND AND MCDONALD ISLANDS','nice_name' => 'Heard Island and Mcdonald Islands','num_code' => NULL,'phone_code' => '0','currency' => '','timezone' => '','status' => '1'),
            array('iso' => 'VA','iso3' => 'VAT','name' => 'HOLY SEE (VATICAN CITY STATE)','nice_name' => 'Holy See (Vatican City State)','num_code' => '336','phone_code' => '39','currency' => '','timezone' => 'Europe/Vatican','status' => '1'),
            array('iso' => 'HN','iso3' => 'HND','name' => 'HONDURAS','nice_name' => 'Honduras','num_code' => '340','phone_code' => '504','currency' => 'HNL','timezone' => 'America/Tegucigalpa','status' => '1'),
            array('iso' => 'HK','iso3' => 'HKG','name' => 'HONG KONG','nice_name' => 'Hong Kong','num_code' => '344','phone_code' => '852','currency' => '','timezone' => 'Asia/Hong_Kong','status' => '1'),
            array('iso' => 'HU','iso3' => 'HUN','name' => 'HUNGARY','nice_name' => 'Hungary','num_code' => '348','phone_code' => '36','currency' => 'HUF','timezone' => 'Europe/Budapest','status' => '1'),
            array('iso' => 'IS','iso3' => 'ISL','name' => 'ICELAND','nice_name' => 'Iceland','num_code' => '352','phone_code' => '354','currency' => 'ISK','timezone' => 'Atlantic/Reykjavik','status' => '1'),
            array('iso' => 'IN','iso3' => 'IND','name' => 'INDIA','nice_name' => 'India','num_code' => '356','phone_code' => '91','currency' => 'INR','timezone' => 'Asia/Kolkata','status' => '1'),
            array('iso' => 'ID','iso3' => 'IDN','name' => 'INDONESIA','nice_name' => 'Indonesia','num_code' => '360','phone_code' => '62','currency' => 'IDR','timezone' => 'Asia/Jakarta','status' => '1'),
            array('iso' => 'IR','iso3' => 'IRN','name' => 'IRAN, ISLAMIC REPUBLIC OF','nice_name' => 'Iran, Islamic Republic of','num_code' => '364','phone_code' => '98','currency' => 'IRR','timezone' => 'Asia/Tehran','status' => '1'),
            array('iso' => 'IQ','iso3' => 'IRQ','name' => 'IRAQ','nice_name' => 'Iraq','num_code' => '368','phone_code' => '964','currency' => 'IQD','timezone' => 'Asia/Baghdad','status' => '1'),
            array('iso' => 'IE','iso3' => 'IRL','name' => 'IRELAND','nice_name' => 'Ireland','num_code' => '372','phone_code' => '353','currency' => 'EUR','timezone' => 'Europe/Dublin','status' => '1'),
            array('iso' => 'IL','iso3' => 'ISR','name' => 'ISRAEL','nice_name' => 'Israel','num_code' => '376','phone_code' => '972','currency' => 'ILS','timezone' => 'Asia/Jerusalem','status' => '1'),
            array('iso' => 'IT','iso3' => 'ITA','name' => 'ITALY','nice_name' => 'Italy','num_code' => '380','phone_code' => '39','currency' => '','timezone' => 'Europe/Rome','status' => '1'),
            array('iso' => 'JM','iso3' => 'JAM','name' => 'JAMAICA','nice_name' => 'Jamaica','num_code' => '388','phone_code' => '1876','currency' => 'JMD','timezone' => 'America/Jamaica','status' => '1'),
            array('iso' => 'JP','iso3' => 'JPN','name' => 'JAPAN','nice_name' => 'Japan','num_code' => '392','phone_code' => '81','currency' => 'JPY','timezone' => 'Asia/Tokyo','status' => '1'),
            array('iso' => 'JO','iso3' => 'JOR','name' => 'JORDAN','nice_name' => 'Jordan','num_code' => '400','phone_code' => '962','currency' => 'JOD','timezone' => 'Asia/Amman','status' => '1'),
            array('iso' => 'KZ','iso3' => 'KAZ','name' => 'KAZAKHSTAN','nice_name' => 'Kazakhstan','num_code' => '398','phone_code' => '7','currency' => 'KZT','timezone' => 'Asia/Almaty','status' => '1'),
            array('iso' => 'KE','iso3' => 'KEN','name' => 'KENYA','nice_name' => 'Kenya','num_code' => '404','phone_code' => '254','currency' => 'KES','timezone' => 'Africa/Nairobi','status' => '1'),
            array('iso' => 'KI','iso3' => 'KIR','name' => 'KIRIBATI','nice_name' => 'Kiribati','num_code' => '296','phone_code' => '686','currency' => 'AUD','timezone' => 'Pacific/Enderbury','status' => '1'),
            array('iso' => 'KP','iso3' => 'PRK','name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','nice_name' => 'Korea, Democratic People\'s Republic of','num_code' => '408','phone_code' => '850','currency' => '','timezone' => 'Asia/Pyongyang','status' => '1'),
            array('iso' => 'KR','iso3' => 'KOR','name' => 'KOREA, REPUBLIC OF','nice_name' => 'Korea, Republic of','num_code' => '410','phone_code' => '82','currency' => '','timezone' => 'Asia/Seoul','status' => '1'),
            array('iso' => 'KW','iso3' => 'KWT','name' => 'KUWAIT','nice_name' => 'Kuwait','num_code' => '414','phone_code' => '965','currency' => 'KWD','timezone' => 'Asia/Kuwait','status' => '1'),
            array('iso' => 'KG','iso3' => 'KGZ','name' => 'KYRGYZSTAN','nice_name' => 'Kyrgyzstan','num_code' => '417','phone_code' => '996','currency' => 'KGS','timezone' => 'Asia/Bishkek','status' => '1'),
            array('iso' => 'LA','iso3' => 'LAO','name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC','nice_name' => 'Lao People\'s Democratic Republic','num_code' => '418','phone_code' => '856','currency' => 'LAK','timezone' => 'Asia/Vientiane','status' => '1'),
            array('iso' => 'LV','iso3' => 'LVA','name' => 'LATVIA','nice_name' => 'Latvia','num_code' => '428','phone_code' => '371','currency' => 'EUR','timezone' => 'Europe/Riga','status' => '1'),
            array('iso' => 'LB','iso3' => 'LBN','name' => 'LEBANON','nice_name' => 'Lebanon','num_code' => '422','phone_code' => '961','currency' => 'LBP','timezone' => 'Asia/Beirut','status' => '1'),
            array('iso' => 'LS','iso3' => 'LSO','name' => 'LESOTHO','nice_name' => 'Lesotho','num_code' => '426','phone_code' => '266','currency' => 'LSL','timezone' => 'Africa/Maseru','status' => '1'),
            array('iso' => 'LR','iso3' => 'LBR','name' => 'LIBERIA','nice_name' => 'Liberia','num_code' => '430','phone_code' => '231','currency' => 'LRD','timezone' => 'Africa/Monrovia','status' => '1'),
            array('iso' => 'LY','iso3' => 'LBY','name' => 'LIBYAN ARAB JAMAHIRIYA','nice_name' => 'Libyan Arab Jamahiriya','num_code' => '434','phone_code' => '218','currency' => 'LYD','timezone' => 'Africa/Tripoli','status' => '1'),
            array('iso' => 'LI','iso3' => 'LIE','name' => 'LIECHTENSTEIN','nice_name' => 'Liechtenstein','num_code' => '438','phone_code' => '423','currency' => 'CHF','timezone' => 'Europe/Vaduz','status' => '1'),
            array('iso' => 'LT','iso3' => 'LTU','name' => 'LITHUANIA','nice_name' => 'Lithuania','num_code' => '440','phone_code' => '370','currency' => 'EUR','timezone' => 'Europe/Vilnius','status' => '1'),
            array('iso' => 'LU','iso3' => 'LUX','name' => 'LUXEMBOURG','nice_name' => 'Luxembourg','num_code' => '442','phone_code' => '352','currency' => 'EUR','timezone' => 'Europe/Luxembourg','status' => '1'),
            array('iso' => 'MO','iso3' => 'MAC','name' => 'MACAO','nice_name' => 'Macao','num_code' => '446','phone_code' => '853','currency' => '','timezone' => 'Asia/Macau','status' => '1'),
            array('iso' => 'MK','iso3' => 'MKD','name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','nice_name' => 'Macedonia, the Former Yugoslav Republic of','num_code' => '807','phone_code' => '389','currency' => '','timezone' => 'Europe/Skopje','status' => '1'),
            array('iso' => 'MG','iso3' => 'MDG','name' => 'MADAGASCAR','nice_name' => 'Madagascar','num_code' => '450','phone_code' => '261','currency' => 'MGA','timezone' => 'Indian/Antananarivo','status' => '1'),
            array('iso' => 'MW','iso3' => 'MWI','name' => 'MALAWI','nice_name' => 'Malawi','num_code' => '454','phone_code' => '265','currency' => 'MWK','timezone' => 'Africa/Blantyre','status' => '1'),
            array('iso' => 'MY','iso3' => 'MYS','name' => 'MALAYSIA','nice_name' => 'Malaysia','num_code' => '458','phone_code' => '60','currency' => 'MYR','timezone' => 'Asia/Kuala_Lumpur','status' => '1'),
            array('iso' => 'MV','iso3' => 'MDV','name' => 'MALDIVES','nice_name' => 'Maldives','num_code' => '462','phone_code' => '960','currency' => 'MVR','timezone' => 'Indian/Maldives','status' => '1'),
            array('iso' => 'ML','iso3' => 'MLI','name' => 'MALI','nice_name' => 'Mali','num_code' => '466','phone_code' => '223','currency' => 'XOF','timezone' => 'Africa/Bamako','status' => '1'),
            array('iso' => 'MT','iso3' => 'MLT','name' => 'MALTA','nice_name' => 'Malta','num_code' => '470','phone_code' => '356','currency' => 'EUR','timezone' => 'Europe/Malta','status' => '1'),
            array('iso' => 'MH','iso3' => 'MHL','name' => 'MARSHALL ISLANDS','nice_name' => 'Marshall Islands','num_code' => '584','phone_code' => '692','currency' => 'USD','timezone' => 'Pacific/Kwajalein','status' => '1'),
            array('iso' => 'MQ','iso3' => 'MTQ','name' => 'MARTINIQUE','nice_name' => 'Martinique','num_code' => '474','phone_code' => '596','currency' => '','timezone' => 'America/Martinique','status' => '1'),
            array('iso' => 'MR','iso3' => 'MRT','name' => 'MAURITANIA','nice_name' => 'Mauritania','num_code' => '478','phone_code' => '222','currency' => 'MRO','timezone' => 'Africa/Nouakchott','status' => '1'),
            array('iso' => 'MU','iso3' => 'MUS','name' => 'MAURITIUS','nice_name' => 'Mauritius','num_code' => '480','phone_code' => '230','currency' => 'MUR','timezone' => 'Indian/Mauritius','status' => '1'),
            array('iso' => 'YT','iso3' => NULL,'name' => 'MAYOTTE','nice_name' => 'Mayotte','num_code' => NULL,'phone_code' => '269','currency' => '','timezone' => 'Indian/Mayotte','status' => '1'),
            array('iso' => 'MX','iso3' => 'MEX','name' => 'MEXICO','nice_name' => 'Mexico','num_code' => '484','phone_code' => '52','currency' => 'MXN','timezone' => 'America/Bahia_Banderas','status' => '1'),
            array('iso' => 'FM','iso3' => 'FSM','name' => 'MICRONESIA, FEDERATED STATES OF','nice_name' => 'Micronesia, Federated States of','num_code' => '583','phone_code' => '691','currency' => '','timezone' => 'Pacific/Chuuk','status' => '1'),
            array('iso' => 'MD','iso3' => 'MDA','name' => 'MOLDOVA, REPUBLIC OF','nice_name' => 'Moldova, Republic of','num_code' => '498','phone_code' => '373','currency' => 'MDL','timezone' => 'Europe/Chisinau','status' => '1'),
            array('iso' => 'MC','iso3' => 'MCO','name' => 'MONACO','nice_name' => 'Monaco','num_code' => '492','phone_code' => '377','currency' => 'EUR','timezone' => 'Europe/Monaco','status' => '1'),
            array('iso' => 'MN','iso3' => 'MNG','name' => 'MONGOLIA','nice_name' => 'Mongolia','num_code' => '496','phone_code' => '976','currency' => 'MNT','timezone' => 'Asia/Choibalsan','status' => '1'),
            array('iso' => 'MS','iso3' => 'MSR','name' => 'MONTSERRAT','nice_name' => 'Montserrat','num_code' => '500','phone_code' => '1664','currency' => 'XCD','timezone' => 'America/Montserrat','status' => '1'),
            array('iso' => 'MA','iso3' => 'MAR','name' => 'MOROCCO','nice_name' => 'Morocco','num_code' => '504','phone_code' => '212','currency' => '','timezone' => 'Africa/Casablanca','status' => '1'),
            array('iso' => 'MZ','iso3' => 'MOZ','name' => 'MOZAMBIQUE','nice_name' => 'Mozambique','num_code' => '508','phone_code' => '258','currency' => 'MZN','timezone' => 'Africa/Maputo','status' => '1'),
            array('iso' => 'MM','iso3' => 'MMR','name' => 'MYANMAR','nice_name' => 'Myanmar','num_code' => '104','phone_code' => '95','currency' => 'MMK','timezone' => 'Asia/Rangoon','status' => '1'),
            array('iso' => 'NA','iso3' => 'NAM','name' => 'NAMIBIA','nice_name' => 'Namibia','num_code' => '516','phone_code' => '264','currency' => 'NAD','timezone' => 'Africa/Windhoek','status' => '1'),
            array('iso' => 'NR','iso3' => 'NRU','name' => 'NAURU','nice_name' => 'Nauru','num_code' => '520','phone_code' => '674','currency' => 'AUD','timezone' => 'Pacific/Nauru','status' => '1'),
            array('iso' => 'NP','iso3' => 'NPL','name' => 'NEPAL','nice_name' => 'Nepal','num_code' => '524','phone_code' => '977','currency' => 'NPR','timezone' => 'Asia/Kathmandu','status' => '1'),
            array('iso' => 'NL','iso3' => 'NLD','name' => 'NETHERLANDS','nice_name' => 'Netherlands','num_code' => '528','phone_code' => '31','currency' => '','timezone' => 'Europe/Amsterdam','status' => '1'),
            array('iso' => 'AN','iso3' => 'ANT','name' => 'NETHERLANDS ANTILLES','nice_name' => 'Netherlands Antilles','num_code' => '530','phone_code' => '599','currency' => '','timezone' => '','status' => '1'),
            array('iso' => 'NC','iso3' => 'NCL','name' => 'NEW CALEDONIA','nice_name' => 'New Caledonia','num_code' => '540','phone_code' => '687','currency' => 'XPF','timezone' => 'Pacific/Noumea','status' => '1'),
            array('iso' => 'NZ','iso3' => 'NZL','name' => 'NEW ZEALAND','nice_name' => 'New Zealand','num_code' => '554','phone_code' => '64','currency' => 'NZD','timezone' => 'Pacific/Auckland','status' => '1'),
            array('iso' => 'NI','iso3' => 'NIC','name' => 'NICARAGUA','nice_name' => 'Nicaragua','num_code' => '558','phone_code' => '505','currency' => 'NIO','timezone' => 'America/Managua','status' => '1'),
            array('iso' => 'NE','iso3' => 'NER','name' => 'NIGER','nice_name' => 'Niger','num_code' => '562','phone_code' => '227','currency' => 'XOF','timezone' => 'Africa/Niamey','status' => '1'),
            array('iso' => 'NG','iso3' => 'NGA','name' => 'NIGERIA','nice_name' => 'Nigeria','num_code' => '566','phone_code' => '234','currency' => 'NGN','timezone' => 'Africa/Lagos','status' => '1'),
            array('iso' => 'NU','iso3' => 'NIU','name' => 'NIUE','nice_name' => 'Niue','num_code' => '570','phone_code' => '683','currency' => 'NZD','timezone' => 'Pacific/Niue','status' => '1'),
            array('iso' => 'NF','iso3' => 'NFK','name' => 'NORFOLK ISLAND','nice_name' => 'Norfolk Island','num_code' => '574','phone_code' => '672','currency' => '','timezone' => 'Pacific/Norfolk','status' => '1'),
            array('iso' => 'MP','iso3' => 'MNP','name' => 'NORTHERN MARIANA ISLANDS','nice_name' => 'Northern Mariana Islands','num_code' => '580','phone_code' => '1670','currency' => '','timezone' => 'Pacific/Saipan','status' => '1'),
            array('iso' => 'NO','iso3' => 'NOR','name' => 'NORWAY','nice_name' => 'Norway','num_code' => '578','phone_code' => '47','currency' => '','timezone' => 'Europe/Oslo','status' => '1'),
            array('iso' => 'OM','iso3' => 'OMN','name' => 'OMAN','nice_name' => 'Oman','num_code' => '512','phone_code' => '968','currency' => 'OMR','timezone' => 'Asia/Muscat','status' => '1'),
            array('iso' => 'PK','iso3' => 'PAK','name' => 'PAKISTAN','nice_name' => 'Pakistan','num_code' => '586','phone_code' => '92','currency' => 'PKR','timezone' => 'Asia/Karachi','status' => '1'),
            array('iso' => 'PW','iso3' => 'PLW','name' => 'PALAU','nice_name' => 'Palau','num_code' => '585','phone_code' => '680','currency' => '','timezone' => 'Pacific/Palau','status' => '1'),
            array('iso' => 'PS','iso3' => NULL,'name' => 'PALESTINIAN TERRITORY, OCCUPIED','nice_name' => 'Palestinian Territory, Occupied','num_code' => NULL,'phone_code' => '970','currency' => '','timezone' => 'Asia/Gaza','status' => '1'),
            array('iso' => 'PA','iso3' => 'PAN','name' => 'PANAMA','nice_name' => 'Panama','num_code' => '591','phone_code' => '507','currency' => 'PAB','timezone' => 'America/Panama','status' => '1'),
            array('iso' => 'PG','iso3' => 'PNG','name' => 'PAPUA NEW GUINEA','nice_name' => 'Papua New Guinea','num_code' => '598','phone_code' => '675','currency' => 'PGK','timezone' => 'Pacific/Bougainville','status' => '1'),
            array('iso' => 'PY','iso3' => 'PRY','name' => 'PARAGUAY','nice_name' => 'Paraguay','num_code' => '600','phone_code' => '595','currency' => 'PYG','timezone' => 'America/Asuncion','status' => '1'),
            array('iso' => 'PE','iso3' => 'PER','name' => 'PERU','nice_name' => 'Peru','num_code' => '604','phone_code' => '51','currency' => 'PEN','timezone' => 'America/Lima','status' => '1'),
            array('iso' => 'PH','iso3' => 'PHL','name' => 'PHILIPPINES','nice_name' => 'Philippines','num_code' => '608','phone_code' => '63','currency' => 'PHP','timezone' => 'Asia/Manila','status' => '1'),
            array('iso' => 'PN','iso3' => 'PCN','name' => 'PITCAIRN','nice_name' => 'Pitcairn','num_code' => '612','phone_code' => '0','currency' => '','timezone' => 'Pacific/Pitcairn','status' => '1'),
            array('iso' => 'PL','iso3' => 'POL','name' => 'POLAND','nice_name' => 'Poland','num_code' => '616','phone_code' => '48','currency' => 'PLN','timezone' => 'Europe/Warsaw','status' => '1'),
            array('iso' => 'PT','iso3' => 'PRT','name' => 'PORTUGAL','nice_name' => 'Portugal','num_code' => '620','phone_code' => '351','currency' => 'EUR','timezone' => 'Atlantic/Azores','status' => '1'),
            array('iso' => 'PR','iso3' => 'PRI','name' => 'PUERTO RICO','nice_name' => 'Puerto Rico','num_code' => '630','phone_code' => '1787','currency' => '','timezone' => 'America/Puerto_Rico','status' => '1'),
            array('iso' => 'QA','iso3' => 'QAT','name' => 'QATAR','nice_name' => 'Qatar','num_code' => '634','phone_code' => '974','currency' => 'QAR','timezone' => 'Asia/Qatar','status' => '1'),
            array('iso' => 'RE','iso3' => 'REU','name' => 'REUNION','nice_name' => 'Reunion','num_code' => '638','phone_code' => '262','currency' => '','timezone' => 'Indian/Reunion','status' => '1'),
            array('iso' => 'RO','iso3' => 'ROM','name' => 'ROMANIA','nice_name' => 'Romania','num_code' => '642','phone_code' => '40','currency' => 'RON','timezone' => 'Europe/Bucharest','status' => '1'),
            array('iso' => 'RU','iso3' => 'RUS','name' => 'RUSSIAN FEDERATION','nice_name' => 'Russian Federation','num_code' => '643','phone_code' => '70','currency' => 'RUB','timezone' => 'Asia/Anadyr','status' => '1'),
            array('iso' => 'RW','iso3' => 'RWA','name' => 'RWANDA','nice_name' => 'Rwanda','num_code' => '646','phone_code' => '250','currency' => 'RWF','timezone' => 'Africa/Kigali','status' => '1'),
            array('iso' => 'SH','iso3' => 'SHN','name' => 'SAINT HELENA','nice_name' => 'Saint Helena','num_code' => '654','phone_code' => '290','currency' => 'SHP','timezone' => 'Atlantic/St_Helena','status' => '1'),
            array('iso' => 'KN','iso3' => 'KNA','name' => 'SAINT KITTS AND NEVIS','nice_name' => 'Saint Kitts and Nevis','num_code' => '659','phone_code' => '1869','currency' => 'XCD','timezone' => 'America/St_Kitts','status' => '1'),
            array('iso' => 'LC','iso3' => 'LCA','name' => 'SAINT LUCIA','nice_name' => 'Saint Lucia','num_code' => '662','phone_code' => '1758','currency' => 'XCD','timezone' => 'America/St_Lucia','status' => '1'),
            array('iso' => 'PM','iso3' => 'SPM','name' => 'SAINT PIERRE AND MIQUELON','nice_name' => 'Saint Pierre and Miquelon','num_code' => '666','phone_code' => '508','currency' => '','timezone' => 'America/Miquelon','status' => '1'),
            array('iso' => 'VC','iso3' => 'VCT','name' => 'SAINT VINCENT AND THE GRENADINES','nice_name' => 'Saint Vincent and the Grenadines','num_code' => '670','phone_code' => '1784','currency' => 'XCD','timezone' => 'America/St_Vincent','status' => '1'),
            array('iso' => 'WS','iso3' => 'WSM','name' => 'SAMOA','nice_name' => 'Samoa','num_code' => '882','phone_code' => '684','currency' => 'WST','timezone' => 'Pacific/Apia','status' => '1'),
            array('iso' => 'SM','iso3' => 'SMR','name' => 'SAN MARINO','nice_name' => 'San Marino','num_code' => '674','phone_code' => '378','currency' => 'EUR','timezone' => 'Europe/San_Marino','status' => '1'),
            array('iso' => 'ST','iso3' => 'STP','name' => 'SAO TOME AND PRINCIPE','nice_name' => 'Sao Tome and Principe','num_code' => '678','phone_code' => '239','currency' => 'STD','timezone' => 'Africa/Sao_Tome','status' => '1'),
            array('iso' => 'SA','iso3' => 'SAU','name' => 'SAUDI ARABIA','nice_name' => 'Saudi Arabia','num_code' => '682','phone_code' => '966','currency' => 'SAR','timezone' => 'Asia/Riyadh','status' => '1'),
            array('iso' => 'SN','iso3' => 'SEN','name' => 'SENEGAL','nice_name' => 'Senegal','num_code' => '686','phone_code' => '221','currency' => 'XOF','timezone' => 'Africa/Dakar','status' => '1'),
            array('iso' => 'CS','iso3' => NULL,'name' => 'SERBIA AND MONTENEGRO','nice_name' => 'Serbia and Montenegro','num_code' => NULL,'phone_code' => '381','currency' => 'RSD','timezone' => '','status' => '1'),
            array('iso' => 'SC','iso3' => 'SYC','name' => 'SEYCHELLES','nice_name' => 'Seychelles','num_code' => '690','phone_code' => '248','currency' => 'SCR','timezone' => 'Indian/Mahe','status' => '1'),
            array('iso' => 'SL','iso3' => 'SLE','name' => 'SIERRA LEONE','nice_name' => 'Sierra Leone','num_code' => '694','phone_code' => '232','currency' => 'SLL','timezone' => 'Africa/Freetown','status' => '1'),
            array('iso' => 'SG','iso3' => 'SGP','name' => 'SINGAPORE','nice_name' => 'Singapore','num_code' => '702','phone_code' => '65','currency' => 'BND','timezone' => 'Asia/Singapore','status' => '1'),
            array('iso' => 'SK','iso3' => 'SVK','name' => 'SLOVAKIA','nice_name' => 'Slovakia','num_code' => '703','phone_code' => '421','currency' => 'EUR','timezone' => 'Europe/Bratislava','status' => '1'),
            array('iso' => 'SI','iso3' => 'SVN','name' => 'SLOVENIA','nice_name' => 'Slovenia','num_code' => '705','phone_code' => '386','currency' => 'EUR','timezone' => 'Europe/Ljubljana','status' => '1'),
            array('iso' => 'SB','iso3' => 'SLB','name' => 'SOLOMON ISLANDS','nice_name' => 'Solomon Islands','num_code' => '90','phone_code' => '677','currency' => 'SBD','timezone' => 'Pacific/Guadalcanal','status' => '1'),
            array('iso' => 'SO','iso3' => 'SOM','name' => 'SOMALIA','nice_name' => 'Somalia','num_code' => '706','phone_code' => '252','currency' => 'SOS','timezone' => 'Africa/Mogadishu','status' => '1'),
            array('iso' => 'ZA','iso3' => 'ZAF','name' => 'SOUTH AFRICA','nice_name' => 'South Africa','num_code' => '710','phone_code' => '27','currency' => 'ZAR','timezone' => 'Africa/Johannesburg','status' => '1'),
            array('iso' => 'GS','iso3' => NULL,'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','nice_name' => 'South Georgia and the South Sandwich Islands','num_code' => NULL,'phone_code' => '0','currency' => '','timezone' => 'Atlantic/South_Georgia','status' => '1'),
            array('iso' => 'ES','iso3' => 'ESP','name' => 'SPAIN','nice_name' => 'Spain','num_code' => '724','phone_code' => '34','currency' => 'EUR','timezone' => 'Africa/Ceuta','status' => '1'),
            array('iso' => 'LK','iso3' => 'LKA','name' => 'SRI LANKA','nice_name' => 'Sri Lanka','num_code' => '144','phone_code' => '94','currency' => 'LKR','timezone' => 'Asia/Colombo','status' => '1'),
            array('iso' => 'SD','iso3' => 'SDN','name' => 'SUDAN','nice_name' => 'Sudan','num_code' => '736','phone_code' => '249','currency' => 'SDG','timezone' => 'Africa/Khartoum','status' => '1'),
            array('iso' => 'SR','iso3' => 'SUR','name' => 'SURINAME','nice_name' => 'Suriname','num_code' => '740','phone_code' => '597','currency' => 'SRD','timezone' => 'America/Paramaribo','status' => '1'),
            array('iso' => 'SJ','iso3' => 'SJM','name' => 'SVALBARD AND JAN MAYEN','nice_name' => 'Svalbard and Jan Mayen','num_code' => '744','phone_code' => '47','currency' => '','timezone' => 'Arctic/Longyearbyen','status' => '1'),
            array('iso' => 'SZ','iso3' => 'SWZ','name' => 'SWAZILAND','nice_name' => 'Swaziland','num_code' => '748','phone_code' => '268','currency' => 'SZL','timezone' => 'Africa/Mbabane','status' => '1'),
            array('iso' => 'SE','iso3' => 'SWE','name' => 'SWEDEN','nice_name' => 'Sweden','num_code' => '752','phone_code' => '46','currency' => 'SEK','timezone' => 'Europe/Stockholm','status' => '1'),
            array('iso' => 'CH','iso3' => 'CHE','name' => 'SWITZERLAND','nice_name' => 'Switzerland','num_code' => '756','phone_code' => '41','currency' => 'CHF','timezone' => 'Europe/Zurich','status' => '1'),
            array('iso' => 'SY','iso3' => 'SYR','name' => 'SYRIAN ARAB REPUBLIC','nice_name' => 'Syrian Arab Republic','num_code' => '760','phone_code' => '963','currency' => 'SYP','timezone' => 'Asia/Damascus','status' => '1'),
            array('iso' => 'TW','iso3' => 'TWN','name' => 'TAIWAN, PROVINCE OF CHINA','nice_name' => 'Taiwan, Province of China','num_code' => '158','phone_code' => '886','currency' => 'TWD','timezone' => 'Asia/Taipei','status' => '1'),
            array('iso' => 'TJ','iso3' => 'TJK','name' => 'TAJIKISTAN','nice_name' => 'Tajikistan','num_code' => '762','phone_code' => '992','currency' => 'TJS','timezone' => 'Asia/Dushanbe','status' => '1'),
            array('iso' => 'TZ','iso3' => 'TZA','name' => 'TANZANIA, UNITED REPUBLIC OF','nice_name' => 'Tanzania, United Republic of','num_code' => '834','phone_code' => '255','currency' => 'TZS','timezone' => 'Africa/Dar_es_Salaam','status' => '1'),
            array('iso' => 'TH','iso3' => 'THA','name' => 'THAILAND','nice_name' => 'Thailand','num_code' => '764','phone_code' => '66','currency' => 'THB','timezone' => 'Asia/Bangkok','status' => '1'),
            array('iso' => 'TL','iso3' => NULL,'name' => 'TIMOR-LESTE','nice_name' => 'Timor-Leste','num_code' => NULL,'phone_code' => '670','currency' => 'USD','timezone' => 'Asia/Dili','status' => '1'),
            array('iso' => 'TG','iso3' => 'TGO','name' => 'TOGO','nice_name' => 'Togo','num_code' => '768','phone_code' => '228','currency' => 'XOF','timezone' => 'Africa/Lome','status' => '1'),
            array('iso' => 'TK','iso3' => 'TKL','name' => 'TOKELAU','nice_name' => 'Tokelau','num_code' => '772','phone_code' => '690','currency' => '','timezone' => 'Pacific/Fakaofo','status' => '1'),
            array('iso' => 'TO','iso3' => 'TON','name' => 'TONGA','nice_name' => 'Tonga','num_code' => '776','phone_code' => '676','currency' => 'TOP','timezone' => 'Pacific/Tongatapu','status' => '1'),
            array('iso' => 'TT','iso3' => 'TTO','name' => 'TRINIDAD AND TOBAGO','nice_name' => 'Trinidad and Tobago','num_code' => '780','phone_code' => '1868','currency' => 'TTD','timezone' => 'America/Port_of_Spain','status' => '1'),
            array('iso' => 'TN','iso3' => 'TUN','name' => 'TUNISIA','nice_name' => 'Tunisia','num_code' => '788','phone_code' => '216','currency' => 'TND','timezone' => 'Africa/Tunis','status' => '1'),
            array('iso' => 'TR','iso3' => 'TUR','name' => 'TURKEY','nice_name' => 'Turkey','num_code' => '792','phone_code' => '90','currency' => 'TRY','timezone' => 'Europe/Istanbul','status' => '1'),
            array('iso' => 'TM','iso3' => 'TKM','name' => 'TURKMENISTAN','nice_name' => 'Turkmenistan','num_code' => '795','phone_code' => '7370','currency' => 'TMT','timezone' => 'Asia/Ashgabat','status' => '1'),
            array('iso' => 'TC','iso3' => 'TCA','name' => 'TURKS AND CAICOS ISLANDS','nice_name' => 'Turks and Caicos Islands','num_code' => '796','phone_code' => '1649','currency' => 'USD','timezone' => 'America/Grand_Turk','status' => '1'),
            array('iso' => 'TV','iso3' => 'TUV','name' => 'TUVALU','nice_name' => 'Tuvalu','num_code' => '798','phone_code' => '688','currency' => 'AUD','timezone' => 'Pacific/Funafuti','status' => '1'),
            array('iso' => 'UG','iso3' => 'UGA','name' => 'UGANDA','nice_name' => 'Uganda','num_code' => '800','phone_code' => '256','currency' => 'UGX','timezone' => 'Africa/Kampala','status' => '1'),
            array('iso' => 'UA','iso3' => 'UKR','name' => 'UKRAINE','nice_name' => 'Ukraine','num_code' => '804','phone_code' => '380','currency' => 'UAH','timezone' => 'Europe/Kiev','status' => '1'),
            array('iso' => 'AE','iso3' => 'ARE','name' => 'UNITED ARAB EMIRATES','nice_name' => 'United Arab Emirates','num_code' => '784','phone_code' => '971','currency' => 'AED','timezone' => 'Asia/Dubai','status' => '1'),
            array('iso' => 'GB','iso3' => 'GBR','name' => 'UNITED KINGDOM','nice_name' => 'United Kingdom','num_code' => '826','phone_code' => '44','currency' => 'GBP','timezone' => 'Europe/London','status' => '1'),
            array('iso' => 'US','iso3' => 'USA','name' => 'UNITED STATES','nice_name' => 'United States','num_code' => '840','phone_code' => '1','currency' => '','timezone' => 'America/Adak','status' => '1'),
            array('iso' => 'UM','iso3' => NULL,'name' => 'UNITED STATES MINOR OUTLYING ISLANDS','nice_name' => 'United States Minor Outlying Islands','num_code' => NULL,'phone_code' => '1','currency' => '','timezone' => 'Pacific/Johnston','status' => '1'),
            array('iso' => 'UY','iso3' => 'URY','name' => 'URUGUAY','nice_name' => 'Uruguay','num_code' => '858','phone_code' => '598','currency' => 'UYU','timezone' => 'America/Montevideo','status' => '1'),
            array('iso' => 'UZ','iso3' => 'UZB','name' => 'UZBEKISTAN','nice_name' => 'Uzbekistan','num_code' => '860','phone_code' => '998','currency' => 'UZS','timezone' => 'Asia/Samarkand','status' => '1'),
            array('iso' => 'VU','iso3' => 'VUT','name' => 'VANUATU','nice_name' => 'Vanuatu','num_code' => '548','phone_code' => '678','currency' => 'VUV','timezone' => 'Pacific/Efate','status' => '1'),
            array('iso' => 'VE','iso3' => 'VEN','name' => 'VENEZUELA','nice_name' => 'Venezuela','num_code' => '862','phone_code' => '58','currency' => 'VEF','timezone' => 'America/Caracas','status' => '1'),
            array('iso' => 'VN','iso3' => 'VNM','name' => 'VIET NAM','nice_name' => 'Viet Nam','num_code' => '704','phone_code' => '84','currency' => 'VND','timezone' => 'Asia/Ho_Chi_Minh','status' => '1'),
            array('iso' => 'VG','iso3' => 'VGB','name' => 'VIRGIN ISLANDS, BRITISH','nice_name' => 'Virgin Islands, British','num_code' => '92','phone_code' => '1284','currency' => '','timezone' => 'America/Tortola','status' => '1'),
            array('iso' => 'VI','iso3' => 'VIR','name' => 'VIRGIN ISLANDS, U.S.','nice_name' => 'Virgin Islands, U.s.','num_code' => '850','phone_code' => '1340','currency' => '','timezone' => 'America/St_Thomas','status' => '1'),
            array('iso' => 'WF','iso3' => 'WLF','name' => 'WALLIS AND FUTUNA','nice_name' => 'Wallis and Futuna','num_code' => '876','phone_code' => '681','currency' => '','timezone' => 'Pacific/Wallis','status' => '1'),
            array('iso' => 'EH','iso3' => 'ESH','name' => 'WESTERN SAHARA','nice_name' => 'Western Sahara','num_code' => '732','phone_code' => '212','currency' => '','timezone' => 'Africa/El_Aaiun','status' => '1'),
            array('iso' => 'YE','iso3' => 'YEM','name' => 'YEMEN','nice_name' => 'Yemen','num_code' => '887','phone_code' => '967','currency' => 'YER','timezone' => 'Asia/Aden','status' => '1'),
            array('iso' => 'ZM','iso3' => 'ZMB','name' => 'ZAMBIA','nice_name' => 'Zambia','num_code' => '894','phone_code' => '260','currency' => 'ZMW','timezone' => 'Africa/Lusaka','status' => '1'),
            array('iso' => 'ZW','iso3' => 'ZWE','name' => 'ZIMBABWE','nice_name' => 'Zimbabwe','num_code' => '716','phone_code' => '263','currency' => 'BWP','timezone' => 'Africa/Harare','status' => '1')
        );

        DB::table('countries')->insert($tb_countries);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }
}
